version: '3.4'

services:
  iotacreator-website:
    image: wordpress
    restart: always
    links:
      - iotacreator-db:db
    volumes:
      - iotacreator-website-vol:/var/www/html
      - ./plugins/all-in-one-wp-migration:/var/www/html/wp-content/plugins/all-in-one-wp-migration
      - ./php-conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  iotacreator-db:
    image: mariadb:10.7
    restart: always
    volumes:
      - iotacreator-db-vol:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: '1'

volumes:
  iotacreator-website-vol:
  iotacreator-db-vol:
